#ifndef	FTM_SWITCH_H_
#define	FTM_SWITCH_H_

#include "ftm_types.h"
#include "ftm_lock.h"

typedef	enum	FTM_SWITCH_TYPE_ENUM
{
	FTM_SWITCH_TYPE_NST = 1,
	FTM_SWITCH_TYPE_DASAN,
	FTM_SWITCH_TYPE_JUNIPER
}	FTM_SWITCH_TYPE, _PTR_ FTM_SWITCH_TYPE_PTR;
	
typedef	struct	FTM_SWITCH_CONFIG_STRUCT
{
	FTM_CHAR		pID[FTM_ID_LEN+1];
	FTM_SWITCH_TYPE	xType;
	FTM_CHAR		pIP[FTM_IP_LEN+1];
	FTM_CHAR		pUser[FTM_USER_LEN+1];
	FTM_CHAR		pPasswd[FTM_PASSWD_LEN+1];
	FTM_CHAR		pComment[FTM_COMMENT_LEN+1];
}	FTM_SWITCH_CONFIG, _PTR_ FTM_SWITCH_CONFIG_PTR;

FTM_RET	FTM_SWITCH_CONFIG_create
(
	FTM_SWITCH_CONFIG_PTR _PTR_ ppConfig
);

FTM_RET	FTM_SWITCH_CONFIG_destroy
(
	FTM_SWITCH_CONFIG_PTR _PTR_ ppConfig
);

typedef	struct	FTM_SWITCH_STRUCT
{
	FTM_SWITCH_CONFIG	xConfig;

	FTM_LOCK			xLock;
}	FTM_SWITCH, _PTR_ FTM_SWITCH_PTR;

FTM_RET	FTM_SWITCH_create
(
	FTM_SWITCH_CONFIG_PTR	pConfig,
	FTM_SWITCH_PTR	_PTR_	ppSwitch
);

FTM_RET	FTM_SWITCH_destroy
(
	FTM_SWITCH_PTR	_PTR_	ppSwitch
);

#endif
