#ifndef	__FTM_SERVER_H__
#define	__FTM_SERVER_H__

#include <sys/socket.h> 
#include <arpa/inet.h>
#include "ftm_types.h"
#include "ftm_params.h"
#include "ftm_list.h"
#include "ftm_time.h"

struct	FTM_CATCHB_STRUCT;

#define	FTM_SERVER_DEFAULT_PORT			8800
#define	FTM_SERVER_DEFAULT_MAX_SESSION	10
#define	FTM_SERVER_DEFAULT_BUFFER_LEN	(FTM_PARAM_MAX_LEN)
#define	FTM_SERVER_DEFAULT_SSID_TIMEOUT	(300)
#define	FTM_PACKET_LEN					(FTM_PARAM_MAX_LEN)

typedef	struct
{
	FTM_UINT16			usPort;
	FTM_UINT32			ulMaxSession;
	FTM_UINT32			ulBufferLen;
	FTM_UINT32			ulSSIDTimeout;
}	FTM_SERVER_CONFIG, _PTR_ FTM_SERVER_CONFIG_PTR;


FTM_RET	FTM_SERVER_CONFIG_setDefault
(
	FTM_SERVER_CONFIG_PTR	pConfig
);

FTM_RET	FTM_SERVER_CONFIG_load
(
	FTM_SERVER_CONFIG_PTR	pConfig,
	cJSON _PTR_ pRoot
);

FTM_RET	FTM_SERVER_CONFIG_save
(
	FTM_SERVER_CONFIG_PTR	pConfig,
	cJSON _PTR_ pRoot
);

FTM_RET	FTM_SERVER_CONFIG_show
(
	FTM_SERVER_CONFIG_PTR	pConfig,
	FTM_TRACE_LEVEL			xLevel
);

typedef	struct
{
	FTM_SERVER_CONFIG	xConfig;

	FTM_CHAR		pName[FTM_NAME_LEN+1];

	struct FTM_CATCHB_STRUCT _PTR_		pCatchB;

	pthread_t 			*pThread ;
	FTM_BOOL			bStop;
	sem_t				xSemaphore;
	pthread_t			xThread;
	FTM_INT				hSocket;
	FTM_LIST			xSessionList;
	FTM_LIST			xReleaseSessionList;
}	FTM_SERVER, _PTR_ FTM_SERVER_PTR;

typedef	struct
{
	FTM_SERVER_PTR		pServer;
	pthread_t 			xThread;	
	FTM_INT				hSocket;
	FTM_BOOL			bStop;
	sem_t				xSemaphore;
	struct sockaddr_in	xPeer;
	FTM_UINT8_PTR		pReqBuff;
	FTM_UINT32			ulReqBufferLen;
	FTM_UINT8_PTR		pRespBuff;
	FTM_UINT32			ulRespBufferLen;
	FTM_TIME			xStartTime;
	FTM_TIME			xLastTime;
}	FTM_SESSION, _PTR_ FTM_SESSION_PTR;

typedef	FTM_RET	(*FTM_SERVICE_CALLBACK)(FTM_SERVER_PTR pServer, FTM_REQ_PARAMS_PTR, FTM_RESP_PARAMS_PTR);

FTM_RET	FTM_SERVER_create
(
	struct FTM_CATCHB_STRUCT _PTR_			pCatchB,
	FTM_SERVER_PTR _PTR_	ppServer
);

FTM_RET	FTM_SERVER_destroy
(
	FTM_SERVER_PTR	_PTR_	ppServer
);

FTM_RET	FTM_SERVER_setConfig
(
	FTM_SERVER_PTR			pServer,
	FTM_SERVER_CONFIG_PTR	pConfig
);

FTM_RET	FTM_SERVER_getConfig
(
	FTM_SERVER_PTR			pServer,
	FTM_SERVER_CONFIG_PTR	pConfig
);

FTM_RET	FTM_SERVER_start
(
	FTM_SERVER_PTR			pServer
);

FTM_RET	FTM_SERVER_stop
(
	FTM_SERVER_PTR			pServer
);

FTM_RET	FTM_SERVER_waitingForFinished
(
	FTM_SERVER_PTR			pServer
);

FTM_RET	FTM_SERVER_serviceCall
(
	FTM_SERVER_PTR			pServer,
	FTM_REQ_PARAMS_PTR		pReq,
	FTM_RESP_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_createSession
(
	FTM_SERVER_PTR pServer,
	FTM_INT			hClient,
	struct sockaddr *pSockAddr,
	FTM_SESSION_PTR _PTR_ ppSession
);

FTM_RET	FTM_SERVER_destroySession
(
	FTM_SERVER_PTR pServer,
	FTM_SESSION_PTR _PTR_ ppSession
);

FTM_RET	FTM_SERVER_getSessionCount
(
	FTM_SERVER_PTR pServer, 
	FTM_UINT32_PTR 	pulCount
);

FTM_RET	FTM_SERVER_getSessionInfo
(
	FTM_SERVER_PTR pServer, 
	FTM_UINT32 			ulIndex, 
	FTM_SESSION_PTR 	pSession
);

FTM_RET	FTM_SERVER_CCTV_add
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_CCTV_ADD_PARAMS_PTR		pReq,
	FTM_RESP_CCTV_ADD_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_CCTV_del
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_CCTV_DEL_PARAMS_PTR		pReq,
	FTM_RESP_CCTV_DEL_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_CCTV_getCount
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_CCTV_GET_COUNT_PARAMS_PTR		pReq,
	FTM_RESP_CCTV_GET_COUNT_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_CCTV_getProperties
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_CCTV_GET_PROPERTIES_PARAMS_PTR	pReq,
	FTM_RESP_CCTV_GET_PROPERTIES_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_CCTV_setProperties
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_CCTV_SET_PROPERTIES_PARAMS_PTR	pReq,
	FTM_RESP_CCTV_SET_PROPERTIES_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_CCTV_getIDList
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_CCTV_GET_ID_LIST_PARAMS_PTR		pReq,
	FTM_RESP_CCTV_GET_ID_LIST_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_CCTV_getList
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_CCTV_GET_LIST_PARAMS_PTR		pReq,
	FTM_RESP_CCTV_GET_LIST_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_CCTV_setPolicy
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_CCTV_SET_POLICY_PARAMS_PTR		pReq,
	FTM_RESP_CCTV_SET_POLICY_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_CCTV_reset
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_CCTV_RESET_PARAMS_PTR		pReq,
	FTM_RESP_CCTV_RESET_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SWITCH_add
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_SWITCH_ADD_PARAMS_PTR		pReq,
	FTM_RESP_SWITCH_ADD_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SWITCH_del
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_SWITCH_DEL_PARAMS_PTR	pReq,
	FTM_RESP_SWITCH_DEL_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SWITCH_getCount
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_SWITCH_GET_COUNT_PARAMS_PTR	pReq,
	FTM_RESP_SWITCH_GET_COUNT_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SWITCH_getProperties
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_SWITCH_GET_PROPERTIES_PARAMS_PTR	pReq,
	FTM_RESP_SWITCH_GET_PROPERTIES_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SWITCH_setProperties
(
	FTM_SERVER_PTR					pServer,
	FTM_REQ_SWITCH_SET_PROPERTIES_PARAMS_PTR	pReq,
	FTM_RESP_SWITCH_SET_PROPERTIES_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SWITCH_getIDList
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_SWITCH_GET_ID_LIST_PARAMS_PTR	pReq,
	FTM_RESP_SWITCH_GET_ID_LIST_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SWITCH_getModelList
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_SWITCH_GET_MODEL_LIST_PARAMS_PTR	pReq,
	FTM_RESP_SWITCH_GET_MODEL_LIST_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SWITCH_getList
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_SWITCH_GET_LIST_PARAMS_PTR	pReq,
	FTM_RESP_SWITCH_GET_LIST_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_LOG_getInfo
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_LOG_GET_INFO_PARAMS_PTR		pReq,
	FTM_RESP_LOG_GET_INFO_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_LOG_getCount
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_LOG_GET_COUNT_PARAMS_PTR	pReq,
	FTM_RESP_LOG_GET_COUNT_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_LOG_getCount2
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_LOG_GET_COUNT2_PARAMS_PTR	pReq,
	FTM_RESP_LOG_GET_COUNT2_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_LOG_getList
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_LOG_GET_LIST_PARAMS_PTR	pReq,
	FTM_RESP_LOG_GET_LIST_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_LOG_del
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_LOG_DEL_PARAMS_PTR	pReq,
	FTM_RESP_LOG_DEL_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_ALARM_add
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_ALARM_ADD_PARAMS_PTR	pReq,
	FTM_RESP_ALARM_ADD_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_ALARM_del
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_ALARM_DEL_PARAMS_PTR	pReq,
	FTM_RESP_ALARM_DEL_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_ALARM_getCount
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_ALARM_GET_COUNT_PARAMS_PTR	pReq,
	FTM_RESP_ALARM_GET_COUNT_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_ALARM_set
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_ALARM_SET_PARAMS_PTR	pReq,
	FTM_RESP_ALARM_SET_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_ALARM_get
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_ALARM_GET_PARAMS_PTR	pReq,
	FTM_RESP_ALARM_GET_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_ALARM_getNameList
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_ALARM_GET_NAME_LIST_PARAMS_PTR	pReq,
	FTM_RESP_ALARM_GET_NAME_LIST_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SMTP_set
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_SMTP_SET_PARAMS_PTR	pReq,
	FTM_RESP_SMTP_SET_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SMTP_get
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_SMTP_GET_PARAMS_PTR	pReq,
	FTM_RESP_SMTP_GET_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_STAT_setInfo
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_STAT_SET_INFO_PARAMS_PTR		pReq,
	FTM_RESP_STAT_SET_INFO_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_STAT_getInfo
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_STAT_GET_INFO_PARAMS_PTR		pReq,
	FTM_RESP_STAT_GET_INFO_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_STAT_getCount
(
	FTM_SERVER_PTR	pServer,
	FTM_REQ_STAT_GET_COUNT_PARAMS_PTR	pReq,
	FTM_RESP_STAT_GET_COUNT_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_STAT_getList
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_STAT_GET_LIST_PARAMS_PTR	pReq,
	FTM_RESP_STAT_GET_LIST_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_STAT_del
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_STAT_DEL_PARAMS_PTR	pReq,
	FTM_RESP_STAT_DEL_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_STAT_del2
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_STAT_DEL2_PARAMS_PTR	pReq,
	FTM_RESP_STAT_DEL2_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SSID_create
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_SSID_CREATE_PARAMS_PTR	pReq,
	FTM_RESP_SSID_CREATE_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SSID_del
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_SSID_DEL_PARAMS_PTR	pReq,
	FTM_RESP_SSID_DEL_PARAMS_PTR	pResp
);

FTM_RET	FTM_SERVER_SSID_verify
(
	FTM_SERVER_PTR pServer, 
	FTM_REQ_SSID_VERIFY_PARAMS_PTR	pReq,
	FTM_RESP_SSID_VERIFY_PARAMS_PTR	pResp
);


#endif
