#ifndef	FTM_DEFAULT_H_
#define	FTM_DEFAULT_H_

#define	FTM_SESSION_ID_LEN		16
#define	FTM_SSID_LEN			16
#define	FTM_ID_LEN				64	
#define	FTM_IP_LEN				24
#define	FTM_USER_LEN			32
#define	FTM_PASSWD_LEN			32
#define	FTM_COMMENT_LEN			64
#define	FTM_NAME_LEN			32
#define	FTM_TIME_LEN			32
#define	FTM_MODEL_LEN			32
#define	FTM_HASH_LEN			48
#define	FTM_HOST_NAME_LEN		256
#define	FTM_LOG_LEN				256
#define	FTM_PATH_LEN			512
#define	FTM_FILE_NAME_LEN		256
#define	FTM_EMAIL_LEN			128
#define	FTM_ALARM_MESSAGE_LEN	1024
#define	FTM_COMMAND_LEN			256

#define	FTM_CATCHB_STATISTICS_COUNT						100
#define	FTM_CATCHB_STATISTICS_UPDATE_INTERVAL			10000
#define	FTM_CATCHB_STATISTICS_UPDATE_INTERVAL_MIN		10000
#define	FTM_CATCHB_STATISTICS_UPDATE_INTERVAL_MAX		3600000

#define	FTM_CATCHB_ANALYZER_DEFAULT_IP_CHECK_INTERVAL	60000
#define	FTM_CATCHB_ANALYZER_MINIMUM_IP_CHECK_INTERVAL	10000
#define	FTM_CATCHB_ANALYZER_DEFAULT_TEST_ENABLE			FTM_FALSE
#define	FTM_CATCHB_ANALYZER_DEFAULT_TEST_ERROR_RATE		10

#define	FTM_CATCHB_NOTIFIER_SYSLOG_ENABLE			FTM_TRUE
#define	FTM_CATCHB_NOTIFIER_SYSLOG_MODE				FTM_NOTIFIER_SYSLOG_MODE_LEVEL
#define	FTM_CATCHB_NOTIFIER_SYSLOG_LEVEL			FTM_LOG_TYPE_ERROR

#define	FTM_CATCHB_DEFAULT_SMTP_ENABLE			FTM_FALSE
#define	FTM_CATCHB_DEFAULT_SMTP_SERVER			"smtp.catchb.com"
#define	FTM_CATCHB_DEFAULT_SMTP_PORT			25
#define	FTM_CATCHB_DEFAULT_SMTP_USER_ID			"admin@catchb.com"
#define	FTM_CATCHB_DEFAULT_SMTP_PASSWD			"admin"
#define	FTM_CATCHB_DEFAULT_SMTP_SENDER			"catchb@catchb.com"

#define	FTM_CATCHB_DB_DEFAULT_DATA_FILE_NAME	"/db/catchb_data.db"
#define	FTM_CATCHB_DB_DEFAULT_LOG_FILE_NAME		"/db/catchb_log.db"

#define	FTM_CATCHB_LOGGER_DEFAULT_RETENTION		30

#define FTM_CATCHB_TRACE_DEFAULT_TIME_FIELD_LEN			20
#define FTM_CATCHB_TRACE_DEFAULT_FUNCTION_FIELD_LEN		24
#define FTM_CATCHB_TRACE_DEFAULT_LINE_FIELD_LEN			4
#define FTM_CATCHB_TRACE_DEFAULT_MODULE_FIELD_LEN		8
#define FTM_CATCHB_TRACE_DEFAULT_LEVEL_FIELD_LEN		4

#define	FTM_CATCHB_TRACE_LOG_SIZE				(1024*1024)

#define	FTM_CATCHB_CLIENT_TMP_PATH				"/mnt/"
#endif
