#ifndef	FTM_PARAMS_H_
#define	FTM_PARAMS_H_

#include "ftm_types.h"
#include "ftm_cctv.h"
#include "ftm_system.h"
#include "ftm_switch.h"
#include "ftm_alarm.h"
#include "ftm_notifier.h"
#include "ftm_utils.h"
#include "ftm_log.h"

#define	FTM_PARAM_MAX_LEN	4096

typedef	enum
{
	FTM_CMD_UNKNOWN,

	FTM_CMD_CCTV_ADD,
	FTM_CMD_CCTV_DEL,
	FTM_CMD_CCTV_SET_PROPERTIES,
	FTM_CMD_CCTV_GET_PROPERTIES,
	FTM_CMD_CCTV_GET_COUNT,
	FTM_CMD_CCTV_GET_ID_LIST,
	FTM_CMD_CCTV_GET_LIST,
	FTM_CMD_CCTV_SET_POLICY,
	FTM_CMD_CCTV_RESET,

	FTM_CMD_SWITCH_ADD,
	FTM_CMD_SWITCH_DEL,
	FTM_CMD_SWITCH_SET_PROPERTIES,
	FTM_CMD_SWITCH_GET_PROPERTIES,
	FTM_CMD_SWITCH_GET_COUNT,
	FTM_CMD_SWITCH_GET_ID_LIST,
	FTM_CMD_SWITCH_GET_LIST,

	FTM_CMD_LOG_GET_INFO,
	FTM_CMD_LOG_GET_COUNT,
	FTM_CMD_LOG_GET_LIST,
	FTM_CMD_LOG_DEL,

	FTM_CMD_ALARM_ADD,
	FTM_CMD_ALARM_DEL,
	FTM_CMD_ALARM_GET_COUNT,
	FTM_CMD_ALARM_GET,
	FTM_CMD_ALARM_SET,
	FTM_CMD_ALARM_GET_NAME_LIST,

	FTM_CMD_SMTP_SET,
	FTM_CMD_SMTP_GET,

	FTM_CMD_STAT_GET_INFO,
	FTM_CMD_STAT_SET_INFO,
	FTM_CMD_STAT_GET_COUNT,
	FTM_CMD_STAT_GET_LIST,
	FTM_CMD_STAT_DEL,
	FTM_CMD_STAT_DEL2,

	FTM_CMD_SSID_CREATE,
	FTM_CMD_SSID_DEL,
	FTM_CMD_SSID_VERIFY,

	FTM_CMD_LOG_GET_COUNT2

}	FTM_CMD, _PTR_ FTM_CMD_PTR;

typedef	struct
{
	FTM_CMD		xCmd;
	FTM_UINT32	ulLen;
	FTM_CHAR	pSSID[FTM_SESSION_ID_LEN+1];
}	FTM_REQ_PARAMS, _PTR_ FTM_REQ_PARAMS_PTR;

typedef	struct
{
	FTM_CMD		xCmd;
	FTM_UINT32	ulLen;
	FTM_RET		xRet;
}	FTM_RESP_PARAMS, _PTR_ FTM_RESP_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pID[FTM_ID_LEN+1];
	FTM_CHAR		pIP[FTM_IP_LEN+1];
	FTM_CHAR		pSwitchID[FTM_ID_LEN+1];
	FTM_CHAR		pComment[FTM_COMMENT_LEN+1];
}	FTM_REQ_CCTV_ADD_PARAMS, _PTR_ FTM_REQ_CCTV_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_CCTV_ADD_PARAMS, _PTR_ FTM_RESP_CCTV_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pID[FTM_ID_LEN+1];
}	FTM_REQ_CCTV_DEL_PARAMS, _PTR_ FTM_REQ_CCTV_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_CCTV_DEL_PARAMS, _PTR_ FTM_RESP_CCTV_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
}	FTM_REQ_CCTV_GET_COUNT_PARAMS, _PTR_ FTM_REQ_CCTV_GET_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
}	FTM_RESP_CCTV_GET_COUNT_PARAMS, _PTR_ FTM_RESP_CCTV_GET_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pID[FTM_ID_LEN+1];
	FTM_UINT32		ulFieldFlags;
	FTM_CCTV_CONFIG	xConfig;
}	FTM_REQ_CCTV_SET_PROPERTIES_PARAMS, _PTR_ FTM_REQ_CCTV_SET_PROPERTIES_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_CCTV_SET_PROPERTIES_PARAMS, _PTR_ FTM_RESP_CCTV_SET_PROPERTIES_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pID[FTM_ID_LEN+1];
}	FTM_REQ_CCTV_GET_PROPERTIES_PARAMS, _PTR_ FTM_REQ_CCTV_GET_PROPERTIES_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_CCTV_CONFIG	xConfig;
}	FTM_RESP_CCTV_GET_PROPERTIES_PARAMS, _PTR_ FTM_RESP_CCTV_GET_PROPERTIES_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
}	FTM_REQ_CCTV_GET_ID_LIST_PARAMS, _PTR_ FTM_REQ_CCTV_GET_ID_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
	FTM_ID			pIDList[];
}	FTM_RESP_CCTV_GET_ID_LIST_PARAMS, _PTR_ FTM_RESP_CCTV_GET_ID_LIST_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
}	FTM_REQ_CCTV_GET_LIST_PARAMS, _PTR_ FTM_REQ_CCTV_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
	FTM_CCTV_CONFIG	pCCTVList[];
}	FTM_RESP_CCTV_GET_LIST_PARAMS, _PTR_ FTM_RESP_CCTV_GET_LIST_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pID[FTM_ID_LEN+1];
	FTM_SWITCH_AC_POLICY	xPolicy;
}	FTM_REQ_CCTV_SET_POLICY_PARAMS, _PTR_ FTM_REQ_CCTV_SET_POLICY_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_CCTV_SET_POLICY_PARAMS, _PTR_ FTM_RESP_CCTV_SET_POLICY_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pID[FTM_ID_LEN+1];
	FTM_CHAR		pHash[FTM_HASH_LEN+1];
}	FTM_REQ_CCTV_RESET_PARAMS, _PTR_ FTM_REQ_CCTV_RESET_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_CCTV_RESET_PARAMS, _PTR_ FTM_RESP_CCTV_RESET_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_SWITCH_CONFIG	xConfig;
}	FTM_REQ_SWITCH_ADD_PARAMS, _PTR_ FTM_REQ_SWITCH_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_SWITCH_ADD_PARAMS, _PTR_ FTM_RESP_SWITCH_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pID[FTM_ID_LEN+1];
}	FTM_REQ_SWITCH_DEL_PARAMS, _PTR_ FTM_REQ_SWITCH_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_SWITCH_DEL_PARAMS, _PTR_ FTM_RESP_SWITCH_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pID[FTM_ID_LEN+1];
	FTM_UINT32		ulFieldFlags;
	FTM_SWITCH_CONFIG	xConfig;
}	FTM_REQ_SWITCH_SET_PROPERTIES_PARAMS, _PTR_ FTM_REQ_SWITCH_SET_PROPERTIES_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_SWITCH_SET_PROPERTIES_PARAMS, _PTR_ FTM_RESP_SWITCH_SET_PROPERTIES_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pID[FTM_ID_LEN+1];
}	FTM_REQ_SWITCH_GET_PROPERTIES_PARAMS, _PTR_ FTM_REQ_SWITCH_GET_PROPERTIES_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_SWITCH_CONFIG	xConfig;
}	FTM_RESP_SWITCH_GET_PROPERTIES_PARAMS, _PTR_ FTM_RESP_SWITCH_GET_PROPERTIES_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
}	FTM_REQ_SWITCH_GET_COUNT_PARAMS, _PTR_ FTM_REQ_SWITCH_GET_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
}	FTM_RESP_SWITCH_GET_COUNT_PARAMS, _PTR_ FTM_RESP_SWITCH_GET_COUNT_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
}	FTM_REQ_SWITCH_GET_ID_LIST_PARAMS, _PTR_ FTM_REQ_SWITCH_GET_ID_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
	FTM_ID			pIDList[];
}	FTM_RESP_SWITCH_GET_ID_LIST_PARAMS, _PTR_ FTM_RESP_SWITCH_GET_ID_LIST_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
}	FTM_REQ_SWITCH_GET_LIST_PARAMS, _PTR_ FTM_REQ_SWITCH_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
	FTM_SWITCH_CONFIG	pSwitchList[];
}	FTM_RESP_SWITCH_GET_LIST_PARAMS, _PTR_ FTM_RESP_SWITCH_GET_LIST_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
}	FTM_REQ_LOG_GET_INFO_PARAMS, _PTR_ FTM_REQ_LOG_GET_INFO_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
	FTM_UINT32		ulFirstTime;
	FTM_UINT32		ulLastTime;
}	FTM_RESP_LOG_GET_INFO_PARAMS, _PTR_ FTM_RESP_LOG_GET_INFO_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
}	FTM_REQ_LOG_GET_COUNT_PARAMS, _PTR_ FTM_REQ_LOG_GET_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
}	FTM_RESP_LOG_GET_COUNT_PARAMS, _PTR_ FTM_RESP_LOG_GET_COUNT_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_LOG_TYPE	xType;
	FTM_CHAR		pID[FTM_ID_LEN+1];
	FTM_CHAR		pIP[FTM_IP_LEN+1];
	FTM_CCTV_STAT	xStat;
	FTM_UINT32		ulBeginTime;
	FTM_UINT32		ulEndTime;
}	FTM_REQ_LOG_GET_COUNT2_PARAMS, _PTR_ FTM_REQ_LOG_GET_COUNT2_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
}	FTM_RESP_LOG_GET_COUNT2_PARAMS, _PTR_ FTM_RESP_LOG_GET_COUNT2_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_LOG_TYPE	xType;
	FTM_CHAR		pID[FTM_ID_LEN+1];
	FTM_CHAR		pIP[FTM_IP_LEN+1];
	FTM_CCTV_STAT	xStat;
	FTM_UINT32		ulBeginTime;
	FTM_UINT32		ulEndTime;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
}	FTM_REQ_LOG_GET_LIST_PARAMS, _PTR_ FTM_REQ_LOG_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
	FTM_LOG			pLogList[];
}	FTM_RESP_LOG_GET_LIST_PARAMS, _PTR_ FTM_RESP_LOG_GET_LIST_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
}	FTM_REQ_LOG_DEL_PARAMS, _PTR_ FTM_REQ_LOG_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
	FTM_UINT32		ulFirstTime;
	FTM_UINT32		ulLastTime;
}	FTM_RESP_LOG_DEL_PARAMS, _PTR_ FTM_RESP_LOG_DEL_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pName[FTM_NAME_LEN+1];
	FTM_CHAR		pEmail[FTM_EMAIL_LEN+1];
	FTM_CHAR		pMessage[FTM_ALARM_MESSAGE_LEN+1];
}	FTM_REQ_ALARM_ADD_PARAMS, _PTR_ FTM_REQ_ALARM_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_ALARM_ADD_PARAMS, _PTR_ FTM_RESP_ALARM_ADD_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pName[FTM_NAME_LEN+1];
}	FTM_REQ_ALARM_DEL_PARAMS, _PTR_ FTM_REQ_ALARM_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_ALARM_DEL_PARAMS, _PTR_ FTM_RESP_ALARM_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
}	FTM_REQ_ALARM_GET_COUNT_PARAMS, _PTR_ FTM_REQ_ALARM_GET_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
}	FTM_RESP_ALARM_GET_COUNT_PARAMS, _PTR_ FTM_RESP_ALARM_GET_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pName[FTM_NAME_LEN+1];
}	FTM_REQ_ALARM_GET_PARAMS, _PTR_ FTM_REQ_ALARM_GET_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
	FTM_ALARM		xAlarm;
}	FTM_RESP_ALARM_GET_PARAMS, _PTR_ FTM_RESP_ALARM_GET_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pName[FTM_NAME_LEN+1];
	FTM_ALARM		xAlarm;
	FTM_UINT32		ulFieldFlags;
}	FTM_REQ_ALARM_SET_PARAMS, _PTR_ FTM_REQ_ALARM_SET_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_ALARM		xAlarm;
}	FTM_RESP_ALARM_SET_PARAMS, _PTR_ FTM_RESP_ALARM_SET_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
}	FTM_REQ_ALARM_GET_NAME_LIST_PARAMS, _PTR_ FTM_REQ_ALARM_GET_NAME_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
	FTM_NAME		pNameList[];
}	FTM_RESP_ALARM_GET_NAME_LIST_PARAMS, _PTR_ FTM_RESP_ALARM_GET_NAME_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_NOTIFIER_SMTP_CONFIG	xSMTP;
}	FTM_REQ_SMTP_SET_PARAMS, _PTR_ FTM_REQ_SMTP_SET_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_NOTIFIER_SMTP_CONFIG	xSMTP;
}	FTM_RESP_SMTP_SET_PARAMS, _PTR_ FTM_RESP_SMTP_SET_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
}	FTM_REQ_SMTP_GET_PARAMS, _PTR_ FTM_REQ_SMTP_GET_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_NOTIFIER_SMTP_CONFIG	xSMTP;
}	FTM_RESP_SMTP_GET_PARAMS, _PTR_ FTM_RESP_SMTP_GET_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_SYSTEM_INFO	xInfo;
}	FTM_REQ_STAT_SET_INFO_PARAMS, _PTR_ FTM_REQ_STAT_SET_INFO_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_SYSTEM_INFO	xInfo;
}	FTM_RESP_STAT_SET_INFO_PARAMS, _PTR_ FTM_RESP_STAT_SET_INFO_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
}	FTM_REQ_STAT_GET_INFO_PARAMS, _PTR_ FTM_REQ_STAT_GET_INFO_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_SYSTEM_INFO	xInfo;
}	FTM_RESP_STAT_GET_INFO_PARAMS, _PTR_ FTM_RESP_STAT_GET_INFO_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
}	FTM_REQ_STAT_GET_COUNT_PARAMS, _PTR_ FTM_REQ_STAT_GET_COUNT_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
}	FTM_RESP_STAT_GET_COUNT_PARAMS, _PTR_ FTM_RESP_STAT_GET_COUNT_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
}	FTM_REQ_STAT_GET_LIST_PARAMS, _PTR_ FTM_REQ_STAT_GET_LIST_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
	FTM_STATISTICS	pStatList[];
}	FTM_RESP_STAT_GET_LIST_PARAMS, _PTR_ FTM_RESP_STAT_GET_LIST_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_UINT32		ulIndex;
	FTM_UINT32		ulCount;
}	FTM_REQ_STAT_DEL_PARAMS, _PTR_ FTM_REQ_STAT_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
	FTM_UINT32		ulFirstTime;
	FTM_UINT32		ulLastTime;
}	FTM_RESP_STAT_DEL_PARAMS, _PTR_ FTM_RESP_STAT_DEL_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_UINT32		ulBeginTime;
	FTM_UINT32		ulEndTime;
}	FTM_REQ_STAT_DEL2_PARAMS, _PTR_ FTM_REQ_STAT_DEL2_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_UINT32		ulCount;
	FTM_UINT32		ulFirstTime;
	FTM_UINT32		ulLastTime;
}	FTM_RESP_STAT_DEL2_PARAMS, _PTR_ FTM_RESP_STAT_DEL2_PARAMS_PTR; 

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
	FTM_CHAR		pID[FTM_ID_LEN+1];
	FTM_CHAR		pPasswd[FTM_PASSWD_LEN+1];
}	FTM_REQ_SSID_CREATE_PARAMS, _PTR_ FTM_REQ_SSID_CREATE_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
	FTM_CHAR		pSSID[FTM_SESSION_ID_LEN+1];
}	FTM_RESP_SSID_CREATE_PARAMS, _PTR_ FTM_RESP_SSID_CREATE_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
}	FTM_REQ_SSID_DEL_PARAMS, _PTR_ FTM_REQ_SSID_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_SSID_DEL_PARAMS, _PTR_ FTM_RESP_SSID_DEL_PARAMS_PTR;

typedef	struct
{
	FTM_REQ_PARAMS	xCommon;
}	FTM_REQ_SSID_VERIFY_PARAMS, _PTR_ FTM_REQ_SSID_VERIFY_PARAMS_PTR;

typedef	struct
{
	FTM_RESP_PARAMS	xCommon;
}	FTM_RESP_SSID_VERIFY_PARAMS, _PTR_ FTM_RESP_SSID_VERIFY_PARAMS_PTR;

#endif
