#ifndef	FTM_SWITCH_DASAN_H_
#define	FTM_SWITCH_DASAN_H_

#include "ftm_types.h"

FTM_RET	FTM_SWITCH_DASAN_setAC
(
	FTM_SWITCH_PTR	pSwitch,
	FTM_CHAR_PTR	pIP,
	FTM_SWITCH_AC_POLICY	xPolicy
);

FTM_RET	FTM_SWITCH_DASAN_setAC2
(
	FTM_SWITCH_PTR	pSwitch,
	FTM_CHAR_PTR	pIP,
	FTM_SWITCH_AC_POLICY	xPolicy
);
#endif

