#ifndef	FTM_LOG_H_
#define	FTM_LOG_H_

#include "ftm_types.h"
#include "ftm_cctv.h"

typedef	enum	FTM_LOG_TYPE_ENUM
{
	FTM_LOG_TYPE_UNKNOWN = 0,
	FTM_LOG_TYPE_NORMAL,
	FTM_LOG_TYPE_ERROR,
	FTM_LOG_TYPE_INFO,
}	FTM_LOG_TYPE, _PTR_ FTM_LOG_TYPE_PTR;

#define	FTM_LOG_OBJ_CCTV	0
#define	FTM_LOG_OBJ_TELNET	4
#define	FTM_LOG_OBJ_SSH		5
#define	FTM_LOG_OBJ_ACL		6

typedef	struct	FTM_LOG_STRUCT
{
	FTM_LOG_TYPE	xType;		
	FTM_UINT32		ulTime;
	FTM_CHAR		pID[FTM_ID_LEN+1];
	FTM_CHAR		pIP[FTM_IP_LEN+1];
	FTM_CHAR		pHash[FTM_HASH_LEN+1];
	FTM_CCTV_STAT	xStat;
}	FTM_LOG, _PTR_ FTM_LOG_PTR;

FTM_CHAR_PTR	FTM_LOG_TYPE_print
(
	FTM_LOG_TYPE	xType
);

FTM_RET	FTM_LOG_add
(
	FTM_LOG_TYPE	xType,
	FTM_UINT32		ulTime,
	FTM_CHAR_PTR	pCCTVID,
	FTM_CHAR_PTR	pIP,
	FTM_CCTV_STAT	xStat,
	FTM_CHAR_PTR	pLog
);
#endif
