#ifndef	CATCHB_TYPES_H_
#define	CATCHB_TYPES_H_

#include <stdint.h>

#define	_PTR_	*

#define	CATCHB_RET	unsigned int

#define	CATCHB_VOID		void
#define	CATCHB_VOID_PTR	void *
#define	CATCHB_BOOL		unsigned int
#define	CATCHB_FALSE	0
#define	CATCHB_TRUE		!(CATCHB_FALSE)

typedef	char			CATCHB_CHAR,	_PTR_ CATCHB_CHAR_PTR;
typedef	unsigned char	CATCHB_UINT8,	_PTR_ CATCHB_UINT8_PTR;
typedef	int				CATCHB_INT,		_PTR_ CATCHB_INT_PTR;
typedef	uint32_t		CATCHB_UINT32, 	_PTR_ CATCHB_UINT32_PTR;

#define	CATCHB_RET_OK						0
#define	CATCHB_RET_ERROR					1
#define	CATCHB_RET_NOT_ENOUGH_MEMORY		2
#define	CATCHB_RET_SEMAPHORE_INIT_FAILED	3	
#define	CATCHB_RET_OBJECT_NOT_FOUND			4
#define	CATCHB_RET_LIST_NOT_INSERTABLE		5
#define	CATCHB_RET_INVALID_ARGUMENTS		6	
#define	CATCHB_RET_LIST_EMPTY				7	
#define	CATCHB_RET_NOT_INITIALIZED			8	
#define	CATCHB_RET_CONFIG_LOAD_FAILED		9 
#define	CATCHB_RET_FAILED_TO_READ_FILE		10
#define	CATCHB_RET_CONFIG_INVALID_OBJECT	11
#define	CATCHB_RET_INVALID_JSON_FORMAT		12
#define	CATCHB_RET_ALREADY_RUNNING			13

#define	CATCHB_ID_LEN			24
#define	CATCHB_IP_LEN			24
#define	CATCHB_PATH_LEN			1024
#define	CATCHB_FILE_NAME_LEN	256
#endif
