#ifndef	CATCHB_DB_H_
#define	CATCHB_DB_H_

#include "catchb_types.h"
#include <sqlite3.h>

#define	CATCHB_DB_QUERY_LEN	1024

typedef	struct	CATCHB_DB_STRUCT
{
	sqlite3 _PTR_	pSQLite3;
}	CATCHB_DB, _PTR_ CATCHB_DB_PTR;

CATCHB_RET	CATCHB_DB_create(CATCHB_DB_PTR _PTR_ pDB);
CATCHB_RET	CATCHB_DB_destroy(CATCHB_DB_PTR _PTR_ pDB);

CATCHB_RET	CATCHB_DB_open(CATCHB_DB_PTR pDB, CATCHB_CHAR_PTR pFileName);
CATCHB_RET	CATCHB_DB_close(CATCHB_DB_PTR pDB);

CATCHB_RET	CATCHB_DB_getAlarmMailInfoCount(CATCHB_DB_PTR pDB, CATCHB_UINT32_PTR pCount);
CATCHB_RET	CATCHB_DB_getAlarmMailInfoList(CATCHB_DB_PTR pDB, CATCHB_ALARM_MAIL_INFO_PTR pAlarmMailList, CATCHB_UINT32 ulMaxCount, CATCHB_UINT32_PTR pCount);
#endif
